module.exports = {
  'MT': 'Mattæusevangeliet',
  'MR': 'Markusevangeliet',
  'LU': 'Lukasevangeliet',
  'JOH': 'Johannesevangeliet',
  'AC': 'Apostlenes Gerninger',
  'RO': 'Romerbrevet',
  '1CO': 'Første Korintherbrev',
  '2CO': 'Andet Korintherbrev',
  'GA': 'Galaterbrevet',
  'EPH': 'Efeserbrevet',
  'PHP': 'Filipperbrevet',
  'COL': 'Kolossenserbrevet',
  '1TH': 'Første Thessalonikerbrev',
  '2TH': 'Andet Thessalonikerbrev',
  '1TI': 'Første Timotheusbrev',
  '2TI': 'Andet Timotheusbrev',
  'TIT': 'Titusbrevet',
  'PHM': 'Filemonbrevet',
  'HEB': 'Hebræerbrevet',
  'JAS': 'Jakobsbrevet',
  '1PE': 'Første Petersbrev',
  '2PE': 'Andet Petersbrev',
  '1JO': 'Første Johannesbrev',
  '2JO': 'Andet Johannesbrev',
  '3JO': 'Tredje Johannesbrev',
  'JUDE': 'Judasbrevet',
  'RE': 'Johannes’ Åbenbaring',
  //GT
  'GEN': 'Første Mosebog',
  'EXOD': 'Anden Mosebog',
  'LEV': 'Tredje Mosebog',
  'NUM': 'Fjerde Mosebog',
  'DEUT': 'Femte Mosebog',
  'JOSH': 'Josvabogen',
  'JUDG': 'Dommerbogen',
  'RUTH': 'Ruths Bog',
  '1SAM': 'Første Samuelsbog',
  '2SAM': 'Anden Samuelsbog',
  '1KGS': 'Første Kongebog',
  '2KGS': 'Anden Kongebog',
  '1CHR': 'Første Krønikebog',
  '2CHR': 'Anden Krønikebog',
  'EZRA': 'Ezras Bog',
  'NEH': 'Nehemias’ Bog',
  'ESTH': 'Esters Bog',
  'JOB': 'Jobs Bog',
  'PS': 'Salmernes Bog',
  'PROV': 'Ordsprogenes Bog',
  'ECCL': 'Prædikerens Bog',
  'SONG': 'Højsangen',
  'ISA': 'Esajas’ Bog',
  'JER': 'Jeremias’ Bog',
  'LAM': 'Klagesangene',
  'EZEK': 'Ezekiels Bog',
  'DAN': 'Daniels Bog',
  'HOS': 'Hoseas’ Bog',
  'JOEL': 'Joels Bog',
  'AMOS': 'Amos’ Bog',
  'OBAD': 'Obadias’ Bog',
  'JONAH': 'Jonas’ Bog',
  'MIC': 'Mikas Bog',
  'NAH': 'Nahmus Bog',
  'HAB': 'Habakkuks Bog',
  'ZEPH': 'Sefanias’ Bog',
  'HAG': 'Haggajs Bog',
  'ZECH': 'Zakarias’ Bog',
  'MAL': 'Malakias’ Bog'
};
